# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
